# Generated by Django 5.2.3 on 2025-07-01 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_account_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
