# Generated by Django 5.2.3 on 2025-07-05 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_already_liked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='already_disliked',
            field=models.ManyToManyField(related_name='already_disliked', to=settings.AUTH_USER_MODEL),
        ),
    ]
