# Generated by Django 5.2.3 on 2025-07-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_already_disliked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='savedpost',
            name='post',
        ),
        migrations.AddField(
            model_name='account',
            name='posts',
            field=models.ManyToManyField(related_name='your_posts', to='posts.post'),
        ),
        migrations.AddField(
            model_name='savedpost',
            name='post',
            field=models.ManyToManyField(related_name='saved_posts', to='posts.post'),
        ),
    ]
