# Generated by Django 5.2.3 on 2025-07-06 05:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_account_posts_remove_savedpost_post_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='already_disliked',
        ),
        migrations.RemoveField(
            model_name='post',
            name='already_liked',
        ),
        migrations.AddField(
            model_name='post',
            name='disliked_by',
            field=models.ManyToManyField(related_name='disliked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='saved_by',
            field=models.ManyToManyField(related_name='saved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SavedPost',
        ),
    ]
